name: Deploy React App to EC2 using Ansible

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Ansible
      run: sudo apt update && sudo apt install -y ansible

    - name: Create private key file
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > mumbai-devops.pem
        chmod 600 mumbai-devops.pem

    - name: Run Ansible Playbook to install Docker
      run: |
        ansible-playbook -i ansible/inventory ansible/setup-docker.yml

    - name: Build Docker image
      run: docker build -t react-cicd .

    - name: Save Docker image as tar
      run: docker save react-cicd | gzip > react-cicd.tar.gz

    - name: Copy image to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "react-cicd.tar.gz"
        target: "/home/${{ secrets.EC2_USER }}/"


    - name: Deploy using Ansible
      run: |
        ansible-playbook -i ansible/inventory ansible/deploy.yml
